import Foundation

struct ChecklistData {
    static let allSections: [SurveySection] = [
        SurveySection(id: "details", title: "Kitchen Details", items: [
            SurveyItem(q: "Type of Kitchen (Jamaat / Faiz / Both)?", type: .text),
            SurveyItem(q: "Condition of Kitchen (Good / Needs Renovation / Requires Attention)?", type: .text),
            SurveyItem(q: "Kitchen Structure (Covered / Partly Covered / Open)?", type: .text),
            SurveyItem(q: "Proper space allotted for different operations?", type: .status)
        ]),
        SurveySection(id: "office", title: "Kitchen Office & Layout", items: [
            SurveyItem(q: "All activities can be monitored from here?", type: .status),
            SurveyItem(q: "Adequate natural light?", type: .status),
            SurveyItem(q: "Adequate electrical, LAN, and telephone connections?", type: .status),
            SurveyItem(q: "Monitoring system (i.e. CCTV)?", type: .status),
            SurveyItem(q: "Desk and chair?", type: .status),
            SurveyItem(q: "Computer and printer?", type: .status),
            SurveyItem(q: "Lockable key cupboard and filing cabinet?", type: .status),
            SurveyItem(q: "Notice board?", type: .status),
            SurveyItem(q: "Condition of Floors (Non-slippery / Sloped)?", type: .text),
            SurveyItem(q: "Appropriate Air flow/Ventilation type (Windows/Exhaust)?", type: .text),
            SurveyItem(q: "Structure & fittings of impermeable material?", type: .status),
            SurveyItem(q: "Wall Protection (Granite/PVC/Corner guards)?", type: .text),
            SurveyItem(q: "Concealed Electric Fixtures?", type: .status),
            SurveyItem(q: "Socket points at suitable height?", type: .status)
        ]),
        SurveySection(id: "amenities", title: "Staff Amenities & Food Handlers", items: [
            SurveyItem(q: "Toilets located away from main kitchen areas?", type: .status),
            SurveyItem(q: "Toilets adequately ventilated?", type: .status),
            SurveyItem(q: "Wash basin provided outside WC?", type: .status),
            SurveyItem(q: "Dust bins and soap dispensers in toilets?", type: .status),
            SurveyItem(q: "Separate uniforms provided for food handlers?", type: .status),
            SurveyItem(q: "Separate kitchen clogs / slippers provided?", type: .status),
            SurveyItem(q: "Medical records of food handlers maintained?", type: .status),
            SurveyItem(q: "Personal belongings removed before entering kitchen?", type: .status),
            SurveyItem(q: "Personal hygiene checked (nails/hair)?", type: .status),
            SurveyItem(q: "Kitchen Outfits worn (Aprons/Gloves/Masks/Hairnets)?", type: .status),
            SurveyItem(q: "Food handlers have necessary food safety knowledge?", type: .status)
        ]),
        SurveySection(id: "janitorial", title: "Janitorial & Kitchen Hygiene", items: [
            SurveyItem(q: "Located away from food preparation areas?", type: .status),
            SurveyItem(q: "Water tap and floor trap for filling/emptying buckets?", type: .status),
            SurveyItem(q: "Mop and brush drying arrangements?", type: .status),
            SurveyItem(q: "Combined wash hand basin and bucket sink?", type: .status),
            SurveyItem(q: "Cobwebs / dust cleaned from ceilings/walls?", type: .status),
            SurveyItem(q: "Area behind and beneath racks/shelves cleaned?", type: .status),
            SurveyItem(q: "Chemicals used for cleaning (QAC based)?", type: .status),
            SurveyItem(q: "Deep cleaning duration (Weekly/15 days)?", type: .text),
            SurveyItem(q: "Deep Cleaning carried out by trained professionals?", type: .status),
            SurveyItem(q: "Water storage tank cleaned (Every 6 months)?", type: .status)
        ]),
        SurveySection(id: "receiving", title: "Goods Receiving Area", items: [
            SurveyItem(q: "Separate from waste disposal and storage areas?", type: .status),
            SurveyItem(q: "Unloading platform: Has vehicular access?", type: .status),
            SurveyItem(q: "Unloading platform: Has waste bins?", type: .status),
            SurveyItem(q: "Unloading platform: Has trolleys?", type: .status),
            SurveyItem(q: "Unloading platform: Has sorting table?", type: .status),
            SurveyItem(q: "Floor surfaces: Slip resistant?", type: .status),
            SurveyItem(q: "Floor surfaces: Easy to clean?", type: .status),
            SurveyItem(q: "Steps have rails / Ramp for trolleys?", type: .status),
            SurveyItem(q: "Inspection of Raw Materials at receival (Haram/Rotten)?", type: .status),
            SurveyItem(q: "Mode of received perishable vegetables (Crates/Sacks)?", type: .text),
            SurveyItem(q: "Temperature of vegetables as received (5°C - 15°C)?", type: .text),
            SurveyItem(q: "Raw Chicken received in proper Crates/Bags?", type: .status)
        ]),
        SurveySection(id: "storage_dry", title: "Goods Storage - Dry Goods", items: [
            SurveyItem(q: "Dry storage in cool area?", type: .status),
            SurveyItem(q: "No items stored in corridors or pathways?", type: .status),
            SurveyItem(q: "Storage area is well ventilated?", type: .status),
            SurveyItem(q: "Windows covered with rust-proof metal nets?", type: .status),
            SurveyItem(q: "Rust-proof cages for potatoes and onions?", type: .status),
            SurveyItem(q: "Racks are sturdy and rust proof?", type: .status),
            SurveyItem(q: "Racks are on lockable castors/wheels?", type: .status),
            SurveyItem(q: "Height adjustable shelves?", type: .status),
            SurveyItem(q: "Shelves are labelled?", type: .status),
            SurveyItem(q: "Packed items stored on Racks (Not on floor)?", type: .status),
            SurveyItem(q: "Grains & Pulses stored on Pallets (Not on floor)?", type: .status),
            SurveyItem(q: "Storage area free from pests?", type: .status),
            SurveyItem(q: "Expiry dates/best before dates checked?", type: .status),
            SurveyItem(q: "Weighing scale present in dry storage?", type: .status),
            SurveyItem(q: "Humidity control (Dehumidifier/AC)?", type: .text),
            SurveyItem(q: "FIFO and FEFO method followed?", type: .status),
            SurveyItem(q: "Record Maintenance (Computerized/Manual)?", type: .text),
            SurveyItem(q: "Racks distance (2\" away from walls / 8\" above ground)?", type: .text)
        ]),
        SurveySection(id: "storage_cold", title: "Goods Storage - Cold Store", items: [
            SurveyItem(q: "Refrigerator less than 5 degrees Celsius?", type: .status),
            SurveyItem(q: "Walk-in fridge/freezer?", type: .status),
            SurveyItem(q: "Condition of Freezer (Outside/Inside)?", type: .text),
            SurveyItem(q: "Freezer rubber gaskets clean?", type: .status),
            SurveyItem(q: "Temperature of frozen items received (-18°C)?", type: .text),
            SurveyItem(q: "Storage Containers (GN Pans/Food Grade)?", type: .text),
            SurveyItem(q: "Non-Veg, Veg & Dairy stored separately?", type: .status),
            SurveyItem(q: "Raw and cooked food stored separately?", type: .status)
        ]),
        SurveySection(id: "hazardous", title: "Hazardous Substances", items: [
            SurveyItem(q: "Cleaning agents/chemicals labelled and color-coded?", type: .status),
            SurveyItem(q: "Stored in lockable closet/space?", type: .status)
        ]),
        SurveySection(id: "airlock", title: "Airlock Lobby", items: [
            SurveyItem(q: "Separates kitchen from other spaces?", type: .status),
            SurveyItem(q: "No storage and free movement?", type: .status),
            SurveyItem(q: "Shoe rack?", type: .status),
            SurveyItem(q: "Cap and glove dispenser?", type: .status),
            SurveyItem(q: "Hand sanitizers?", type: .status)
        ]),
        SurveySection(id: "prep_veg", title: "Preparation Area (General & Veg)", items: [
            SurveyItem(q: "Water supply is treated (RO)?", type: .status),
            SurveyItem(q: "Equipment easy to move for cleaning?", type: .status),
            SurveyItem(q: "Food contact surfaces non-absorbent?", type: .status),
            SurveyItem(q: "Sorting of vegetables before processing?", type: .status),
            SurveyItem(q: "Vegetables washing (Before Cutting)?", type: .status),
            SurveyItem(q: "Separate processing of Veg & Non-Veg items?", type: .status),
            SurveyItem(q: "Separate Accessories (Knives/Boards) for Veg & Non-Veg?", type: .status),
            SurveyItem(q: "Colour Coded Chopping Boards used?", type: .status),
            SurveyItem(q: "Condition of chopping boards/tables?", type: .text),
            SurveyItem(q: "Defrosting (thawing) method (Fridge/Running Water)?", type: .text),
            SurveyItem(q: "Separate bins for Wet & Dry waste?", type: .status),
            SurveyItem(q: "Condition of garbage bins?", type: .text)
        ]),
        SurveySection(id: "prep_meat", title: "Meat Preparation Area", items: [
            SurveyItem(q: "Wash hand basins at convenient location?", type: .status),
            SurveyItem(q: "Adequate floor drainage gullies?", type: .status),
            SurveyItem(q: "Wash basin with foot/knee operated taps?", type: .status),
            SurveyItem(q: "No cross-contamination from wash basin?", type: .status),
            SurveyItem(q: "Hot water in wash basins?", type: .status),
            SurveyItem(q: "Sinks adequately sized?", type: .status),
            SurveyItem(q: "Fixtures are stainless steel?", type: .status),
            SurveyItem(q: "Type of Knives (SS Carbonated/High Carbon)?", type: .text),
            SurveyItem(q: "Condition of knives (Sharpened/Clean)?", type: .status),
            SurveyItem(q: "Floor Hygiene (Properly clean)?", type: .status),
            SurveyItem(q: "Type of drainage system (Open/Closed)?", type: .text)
        ]),
        SurveySection(id: "cooking", title: "Cooking Area", items: [
            SurveyItem(q: "Cooking Area has filtered/treated water available?", type: .status),
            SurveyItem(q: "Condition of Utensils (Copper/SS)?", type: .text),
            SurveyItem(q: "Duration of kalai (40 Days)?", type: .text),
            SurveyItem(q: "Types of Stoves (SS Body)?", type: .text),
            SurveyItem(q: "Type of Gas Connection (Metered/Cylinder)?", type: .text),
            SurveyItem(q: "Type of Ventilation System (Exhaust/Hood)?", type: .text),
            SurveyItem(q: "Floor drain channels available?", type: .status),
            SurveyItem(q: "Condition of Appliances?", type: .text),
            SurveyItem(q: "Appliances maintenance done (Monthly)?", type: .text),
            SurveyItem(q: "Is floor non-slippery?", type: .status)
        ]),
        SurveySection(id: "taste", title: "Taste & Quality", items: [
            SurveyItem(q: "Duration between cutting and cooking (< 2 hrs)?", type: .text),
            SurveyItem(q: "Processed food kept in controlled temperature?", type: .status),
            SurveyItem(q: "Type of Pasaw tokri (Stainless Steel)?", type: .text),
            SurveyItem(q: "Rice grains washed before soaking?", type: .status),
            SurveyItem(q: "Muminaat involvement in menu planning?", type: .status),
            SurveyItem(q: "Periodic verification of oil (Rancidity)?", type: .text),
            SurveyItem(q: "Nutritional value checked?", type: .status),
            SurveyItem(q: "Supervision by members while Cooking?", type: .status),
            SurveyItem(q: "Feedback system (Daily/Weekly)?", type: .text),
            SurveyItem(q: "Cooling method (Blast chillers/Fans)?", type: .text),
            SurveyItem(q: "Holding method (Perforated Lids)?", type: .text),
            SurveyItem(q: "Mumeneen informed regularly (Storing/Serving)?", type: .status)
        ]),
        SurveySection(id: "thaali", title: "Thaali Filling & Distribution", items: [
            SurveyItem(q: "Away from thaali collection area?", type: .status),
            SurveyItem(q: "Enclosed area to prevent animals and pests?", type: .status),
            SurveyItem(q: "Thali filling done on SS Tables?", type: .status),
            SurveyItem(q: "Empty Tiffins kept on Rack/Crates?", type: .status),
            SurveyItem(q: "Type of containers (SS Tiffin/Food grade)?", type: .text),
            SurveyItem(q: "Delivery vehicle enclosed/sealed?", type: .status),
            SurveyItem(q: "Delivery Vehicle cleaned/sanitized?", type: .status),
            SurveyItem(q: "Chemicals transported separately?", type: .status),
            SurveyItem(q: "Filled Tiffins kept in Food Grade Crates?", type: .status),
            SurveyItem(q: "Crates/bags washed & sanitized?", type: .status)
        ]),
        SurveySection(id: "butchery", title: "Zabihat & Butchery", items: [
            SurveyItem(q: "Secluded entrance?", type: .status),
            SurveyItem(q: "Curbed-in bleeding area to avoid splashing?", type: .status),
            SurveyItem(q: "Flooring is non-absorbent/crack-free?", type: .status),
            SurveyItem(q: "Water supply/drainage provided?", type: .status),
            SurveyItem(q: "Weighing scale available?", type: .status),
            SurveyItem(q: "Stainless steel tables/hooks?", type: .status),
            SurveyItem(q: "Plastic chopping boards (Colour Coded)?", type: .text),
            SurveyItem(q: "Sink/hand-wash basin with hot/cold water?", type: .status),
            SurveyItem(q: "Changing of Mitti before each zabihat?", type: .status),
            SurveyItem(q: "Knives Condition (Sharpened/No Rust)?", type: .status),
            SurveyItem(q: "Processed meat stored in GN Pans?", type: .status),
            SurveyItem(q: "Cleaning & disinfecting done with Antibacterial agents?", type: .status),
            SurveyItem(q: "Temperature of Meat processing area controlled?", type: .status),
            SurveyItem(q: "Blood stains residues cleaned?", type: .status),
            SurveyItem(q: "Proper ventilation system?", type: .status),
            SurveyItem(q: "Trays available for zabihat?", type: .status)
        ]),
        SurveySection(id: "roti", title: "Roti Making Area", items: [
            SurveyItem(q: "Separate from main kitchen area?", type: .status),
            SurveyItem(q: "Sufficient ventilation?", type: .status),
            SurveyItem(q: "Sink with hot and cold water available?", type: .status),
            SurveyItem(q: "Condition of Equipment (Dough Mixer/Hot Plate)?", type: .text),
            SurveyItem(q: "Roti making done on Work Tables?", type: .status),
            SurveyItem(q: "Condition of Patla & Velan?", type: .text),
            SurveyItem(q: "Cleaning & sanitization carried out?", type: .status)
        ]),
        SurveySection(id: "potwash", title: "Pot Wash Area", items: [
            SurveyItem(q: "Adequate space?", type: .status),
            SurveyItem(q: "High pressure hoses for easy cleaning?", type: .status),
            SurveyItem(q: "Adequate ventilation?", type: .status),
            SurveyItem(q: "Adequate floor drainage with slope?", type: .status),
            SurveyItem(q: "Wall-mounted liquid soap dispenser?", type: .status),
            SurveyItem(q: "Sufficient space for washing largest degh?", type: .status),
            SurveyItem(q: "Hot & Cold water supply available?", type: .status),
            SurveyItem(q: "Type of cleaning agents (Detergents/Liquid)?", type: .text),
            SurveyItem(q: "Drying of utensils (Drying Racks)?", type: .text),
            SurveyItem(q: "Cleaning & sanitization carried out?", type: .status)
        ]),
        SurveySection(id: "pest", title: "Pest Control", items: [
            SurveyItem(q: "Type of dustbins (Foot Operated/Covered)?", type: .text),
            SurveyItem(q: "Risks for Pest (Open drains/Garbage)?", type: .status),
            SurveyItem(q: "Pest Control Duration (Monthly)?", type: .text),
            SurveyItem(q: "Pest control performed by Trained personnel?", type: .status),
            SurveyItem(q: "Pest Protection (Air Curtains/Fly Door)?", type: .text),
            SurveyItem(q: "Mesh / Nets on Ventilations?", type: .status)
        ]),
        SurveySection(id: "safety", title: "Safety, Fire & Utilities", items: [
            SurveyItem(q: "Is Operative Calendar followed?", type: .status),
            SurveyItem(q: "Gas Bank in designated area?", type: .status),
            SurveyItem(q: "Testing of potable water (NABL Labs)?", type: .text),
            SurveyItem(q: "RO Filter regular checking?", type: .status),
            SurveyItem(q: "Emergency devices (Extinguishers/Blankets)?", type: .text),
            SurveyItem(q: "Emergency Light Facility?", type: .status),
            SurveyItem(q: "Safety sign boards present?", type: .status),
            SurveyItem(q: "First Aid Box available?", type: .status),
            SurveyItem(q: "Fire exits available?", type: .status)
        ])
    ]
}
